name: CI

on:
  push:
    branches:
      - master
  pull_request:
  create:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: docker build . -t stanza-base:latest

      - name: Install Cinc
        run: |
          curl -L https://omnitruck.cinc.sh/install.sh | \
          sudo bash -s -- -P cinc-auditor -v 4

      - name: Install Gomplate
        run: |
          curl -L \
            https://github.com/hairyhenderson/gomplate/releases/download/v3.9.0/gomplate_linux-amd64 \
            -o gomplate
          chmod +x gomplate

      - name: Start Test Container
        run: |
          docker run -d \
            --name test \
            --entrypoint=/bin/sleep \
            stanza-base:latest 3600

      - name: Generate Tests
        run: |
          ./gomplate \
            --datasource data=dependencies.json \
            --file test/integration.template > test/integration.rb

      - name: Run Tests
        run: cinc-auditor exec test/integration.rb -t docker://test

      - name: Get Tag
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}
        if: github.event_name == 'create'

      - name: Release
        run: ./scripts/release.sh
        env:
            GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
            IMAGE_NAME: stanza-base
            IMAGE_TAG: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}
        if: github.event_name == 'create'


             