name: CI

on:
  push:
    branches:
      - master
  pull_request:
  create:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        run: docker build . -t stanza-base:latest

      - name: Export Image
        run: docker save -o /tmp/stanza-base.tar stanza-base:latest

      - name: Share Exported Image
        uses: actions/upload-artifact@v2
        with:
          name: stanza-base
          path: /tmp/stanza-base.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Cinc
        run: |
          curl -L https://omnitruck.cinc.sh/install.sh | \
          sudo bash -s -- -P cinc-auditor -v 4

      - name: Download Image
        uses: actions/download-artifact@v2
        with:
          name: stanza-base
          path: /tmp

      - name: Load Image
        run: |
          docker load < /tmp/stanza-base.tar

      - name: Start Test Container
        run: |
          docker run -d \
            --name test \
            --entrypoint=/bin/sleep \
            stanza-base:latest 3600

      - name: Run Tests
        run: cinc-auditor exec test/integration.rb -t docker://test

  release:
    needs: test
    # skip release unless new tag triggered the workflow
    if: github.event_name == 'create'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Image
        uses: actions/download-artifact@v2
        with:
          name: stanza-base
          path: /tmp

      - name: Load Image
        run: |
          docker load < /tmp/stanza-base.tar

      - name: Get Tag
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}

      - name: Release
        run: ./scripts/release.sh
        env:
            GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
            IMAGE_NAME: stanza-base
            IMAGE_TAG: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}