name: CI

on:
  push:
    branches:
      - master
  pull_request:
  create:
    tags:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Latest Docker
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable"
          sudo apt-get update
          sudo apt-get install docker-ce

      - name: Check Docker Version
        run: docker --version

      - name: Configure Docker Buildx
        run: |
          mkdir -p ~/.docker/cli-plugins
          curl -fL https://github.com/docker/buildx/releases/download/v0.6.1/buildx-v0.6.1.linux-amd64 -o ~/.docker/cli-plugins/docker-buildx
          chmod a+x ~/.docker/cli-plugins/docker-buildx
          docker buildx create --name stanza --driver docker-container --use
          docker buildx inspect --bootstrap

      - name: Build Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag stanza-base:latest \
            --build-arg dependencies="$(jq -r 'to_entries | .[] | .key + "=" + .value' dependencies.json)" \
            .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

      - name: Install Cinc
        run: |
          curl -L https://omnitruck.cinc.sh/install.sh | \
          sudo bash -s -- -P cinc-auditor -v 4

      - name: Install Gomplate
        run: |
          curl -L \
            https://github.com/hairyhenderson/gomplate/releases/download/v3.9.0/gomplate_linux-amd64 \
            -o gomplate
          chmod +x gomplate

      - name: Start Test Container
        run: |
          docker run -d \
            --name test \
            --entrypoint=/bin/sleep \
            stanza-base:latest 3600

      - name: Generate Tests
        run: |
          ./gomplate \
            --datasource data=dependencies.json \
            --file test/integration.template > test/integration.rb

      - name: Run Tests
        run: cinc-auditor exec test/integration.rb -t docker://test

      - name: Get Tag
        id: get_tag_name
        run: echo ::set-output name=GIT_TAG_NAME::${GITHUB_REF/refs\/tags\//}

      - name: Release
        run: ./scripts/release.sh
        env:
            GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
            IMAGE_NAME: stanza-base
            IMAGE_TAG: ${{ steps.get_tag_name.outputs.GIT_TAG_NAME}}


             