name: Dependencies
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  updates:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    # run script inside docker image ubuntu:22.04 to match
    # the base image used in this repo's Dockerfile. Github actions
    # is running in ubuntu 20.04, which will not give us the correct
    # apt package versions
    - name: Update dependencies
      run: |
        docker run \
          -v $(pwd):/repo \
          -w /repo ubuntu:22.04 \
          sh scripts/update_dependencies.sh
    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "chore(deps): update dependencies.json"
        branch: features/update-dependencies
        title: Update APT packages
        body: Updated dependencies.json
        delete-branch: true
        labels: dependencies
        reviewers: jsirianni
