name: Linter
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: |
          docker run --rm -i \
            --entrypoint=/bin/hadolint hadolint/hadolint - \
            --ignore DL3008 \
            --ignore DL4006 \
            < Dockerfile