
---
name: shellcheck
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Shellcheck ./scripts/
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './scripts/'
